server:
  port: 8443
  ssl:
    enabled: true
    key-store: classpath:server.p12
    key-store-password: changeit
    key-store-type: PKCS12
    key-alias: server
#    client-auth: need   # ⬅️ require client certificate
#    client-auth: want   # ⬅️ require client certificate
